project:
  type: website

website:
  title: "Climate Change Effects On The World"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Marine.qmd
      - Research.qmd
      - solution.qmd
      - closing.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



