---
title: "Research"
---
## Effects of High and Low Temperatures on Sea Level Pressure

```{r}
#| echo: false
#| message: false

library(readr)
library(tidyverse)
library(ggplot2)
library(lubridate)
read_rds("pressure.rds")
```



## A decrease in sea level pressure can lead to several effects, including:

-Weather patterns: a decrease in sea level pressure is often associated with low pressure systems, which can bring storms, rain, and windy conditions.

-Coastal erosion: Lower sea level pressure can result in stronger onshore winds, which can increase wave heights and cause coastal erosion.

-Changes in marine life: The change in pressure can cause disruptions in ocean currents and water temperature, affecting the distribution and behavior of marine animals and plants.

-Agricultural impacts: A decrease in sea level pressure can lead to changes in temperature and precipitation patterns, which can affect crops and agricultural production.

-Human health: The increased wind and rain associated with low sea level pressure can lead to increased respiratory problems, as well as an increased risk of flooding and landslides in some areas.

-It's important to note that a decrease in sea level pressure can be a result of various weather patterns, and its effects can vary depending on the specific location and conditions.


## An increase in sea level pressure is often associated with high pressure systems and can result in several effects, including:

-Better weather conditions: Higher sea level pressure is often accompanied by clear skies, low winds, and warmer temperatures.

-Decreased coastal erosion: Higher sea level pressure can lead to weaker onshore winds, reducing the risk of coastal erosion and wave damage.

-Changes in marine life: Increased sea level pressure can change the distribution and behavior of marine animals and plants, affecting the balance of marine ecosystems.

-Agricultural impacts: The change in pressure can alter temperature and precipitation patterns, potentially affecting crop growth and agricultural production.

-Human health: Higher sea level pressure can lead to improved air quality, with fewer pollutants being transported from the ground to the atmosphere.

-It's important to note that an increase in sea level pressure can be a result of various weather patterns, and its effects can vary depending on the specific location and conditions.